import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  ar: {
    common: {
      appName: "All In One",
      shortName: "AIO",
      save: "حفظ التغييرات",
      cancel: "إلغاء",
      loading: "جاري التحميل...",
      saving: "جاري الحفظ...",
      success: "تمت العملية بنجاح",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      language: "اللغة",
      arabic: "العربية",
      english: "English",
      light: "فاتح",
      dark: "داكن",
      system: "حسب الجهاز",
      online: "متصل الآن",
      back: "رجوع",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور"
    },
    validation: {
      required: "هذا الحقل مطلوب",
      email: "اكتب بريداً إلكترونياً صحيحاً",
      password: "استخدم 8 أحرف على الأقل، تشمل حرفاً كبيراً ورقماً",
      passwordMatch: "كلمتا المرور غير متطابقتين",
      name: "اكتب اسماً لا يقل عن حرفين",
      otp: "أدخل رمز التحقق المكون من 6 أرقام",
      terms: "يجب الموافقة على الشروط وسياسة الخصوصية",
      imageType: "استخدم صورة PNG أو JPG أو WebP",
      imageSize: "حجم الصورة يجب ألا يتجاوز 2 ميجابايت"
    },
    auth: {
      secureAccess: "دخول آمن لمساحة عملك",
      secureDescription: "حساب واحد يوجهك تلقائياً إلى تجربتك المناسبة حسب صلاحياتك.",
      signIn: "تسجيل الدخول",
      signInSubtitle: "أدخل بيانات حسابك وسنوجهك تلقائياً إلى مساحة العمل الصحيحة.",
      signingIn: "جاري تسجيل الدخول...",
      remember: "تذكرني على هذا الجهاز",
      forgot: "نسيت كلمة المرور؟",
      noAccount: "ليس لديك حساب؟",
      createAccount: "إنشاء حساب جديد",
      createTitle: "ابدأ بحسابك الشخصي",
      createSubtitle: "أنشئ حساباً آمناً، ثم انضم إلى شركتك من خلال الدعوة المرسلة إلى نفس البريد.",
      fullName: "الاسم الكامل",
      confirmPassword: "تأكيد كلمة المرور",
      agreePrefix: "أوافق على",
      terms: "شروط الاستخدام",
      privacy: "سياسة الخصوصية",
      creating: "جاري إنشاء الحساب...",
      haveAccount: "لديك حساب بالفعل؟",
      verifyTitle: "تأكيد البريد الإلكتروني",
      verifySubtitle: "أدخل الرمز المكون من 6 أرقام الذي أرسلناه إلى",
      verify: "تأكيد البريد",
      verifying: "جاري التحقق...",
      resend: "إعادة إرسال الرمز",
      resendIn: "يمكن إعادة الإرسال خلال",
      codeSent: "تم إرسال رمز جديد إلى بريدك",
      forgotTitle: "استعادة كلمة المرور",
      forgotSubtitle: "أدخل بريدك وسنرسل لك رمزاً آمناً لإعادة تعيين كلمة المرور.",
      sendCode: "إرسال رمز الاستعادة",
      sending: "جاري الإرسال...",
      resetTitle: "إنشاء كلمة مرور جديدة",
      resetSubtitle: "اختر كلمة مرور قوية ومختلفة عن كلمات المرور السابقة.",
      resetCode: "رمز الاستعادة",
      newPassword: "كلمة المرور الجديدة",
      reset: "حفظ كلمة المرور",
      passwordRules: "8 أحرف على الأقل، حرف كبير، حرف صغير، ورقم",
      resetSuccess: "تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن.",
      backToLogin: "العودة لتسجيل الدخول",
      testAccounts: "حسابات التجربة",
      testHint: "اختر حساباً لتعبئة البيانات وتجربة الصلاحيات المختلفة.",
      superAdmin: "مسؤول المنصة",
      companyAdmin: "مسؤول الشركة",
      endUser: "مستخدم نهائي",
      loginSuccess: "تم تسجيل الدخول بنجاح",
      loginError: "تعذر تسجيل الدخول",
      accountCreated: "تم إنشاء الحساب وإرسال رمز التحقق",
      verified: "تم تأكيد بريدك بنجاح",
      resetCodeSent: "تم إرسال رمز الاستعادة إلى بريدك",
      demoCode: "رمز التجربة: 123456"
      ,invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
      accountExists: "يوجد حساب مسجل بهذا البريد بالفعل",
      invalidCode: "رمز التحقق غير صحيح أو انتهت صلاحيته",
      accountNotFound: "لا يوجد حساب مسجل بهذا البريد",
      registrationExpired: "انتهت جلسة التسجيل. ابدأ إنشاء الحساب مرة أخرى",
      authRequired: "يجب تسجيل الدخول لإكمال هذه العملية",
      currentPasswordIncorrect: "كلمة المرور الحالية غير صحيحة"
    },
    shell: {
      search: "ابحث عن الغرف، الملفات أو الأعضاء...",
      searchLabel: "البحث في مساحة العمل",
      notifications: "الإشعارات",
      accountMenu: "قائمة الحساب",
      settings: "الإعدادات",
      appearance: "المظهر",
      logout: "تسجيل الخروج",
      help: "مركز المساعدة",
      upgrade: "ترقية الباقة",
      menu: "فتح القائمة",
      closeMenu: "إغلاق القائمة",
      dashboard: "لوحة التحكم",
      home: "الرئيسية",
      rooms: "الغرف",
      files: "مكتبة المحتوى",
      members: "الأعضاء",
      courses: "البرامج والكورسات",
      batches: "الدفعات والمجموعات",
      bookingRequests: "طلبات الحجز",
      announcements: "الإعلانات",
      meetings: "الاجتماعات",
      tasks: "المهام",
      calendar: "التقويم",
      bookings: "احجز مع مدرس",
      analytics: "التحليلات",
      security: "الأمان",
      subscription: "الاشتراك",
      tenants: "المؤسسات",
      revenue: "الإيرادات",
      subscriptions: "الاشتراكات",
      pricing: "الباقات والأسعار",
      activity: "سجل النشاط",
      footerRights: "جميع الحقوق محفوظة.",
      privacy: "سياسة الخصوصية",
      terms: "شروط الخدمة",
      support: "الدعم الفني"
    },
    settings: {
      title: "إعدادات الحساب",
      subtitle: "تحكم في بياناتك وأمانك وتفضيلات تجربة الاستخدام.",
      profile: "الملف الشخصي",
      security: "الأمان وتسجيل الدخول",
      notifications: "الإشعارات",
      appearance: "المظهر واللغة",
      profileDescription: "حدّث صورتك واسمك وبيانات التواصل الخاصة بك.",
      photo: "الصورة الشخصية",
      photoHint: "PNG أو JPG أو WebP، بحد أقصى 2 ميجابايت.",
      changePhoto: "تغيير الصورة",
      removePhoto: "حذف الصورة",
      role: "نوع الحساب",
      company: "مساحة العمل",
      profileSaved: "تم حفظ بيانات الحساب",
      securityDescription: "أدر كلمة المرور ووسائل التحقق الإضافية لحماية حسابك.",
      currentPassword: "كلمة المرور الحالية",
      changePassword: "تغيير كلمة المرور",
      twoFactor: "التحقق بخطوتين",
      authenticator: "تطبيق المصادقة",
      authenticatorHint: "استخدم تطبيقاً لإنشاء رمز مؤقت عند تسجيل الدخول.",
      sms: "رسائل SMS",
      smsHint: "استقبل رمزاً على رقم الهاتف المسجل.",
      sessions: "الجلسات النشطة",
      sessionsHint: "هذا الجهاز · القاهرة، مصر · نشط الآن",
      signOutOthers: "تسجيل خروج الأجهزة الأخرى",
      notificationDescription: "اختر متى وكيف تريد استقبال التنبيهات.",
      emailNotifications: "إشعارات البريد الإلكتروني",
      emailNotificationsHint: "الملفات الجديدة والدعوات وتحديثات مساحة العمل.",
      securityAlerts: "تنبيهات الأمان",
      securityAlertsHint: "محاولات الدخول والأجهزة الجديدة والتغييرات الحساسة.",
      productUpdates: "تحديثات المنتج",
      productUpdatesHint: "الميزات الجديدة والتحسينات المهمة.",
      appearanceDescription: "خصص المظهر واللغة بدون التأثير على بيانات الحساب.",
      theme: "نمط العرض",
      accent: "لون الواجهة",
      interfaceLanguage: "لغة الواجهة",
      settingsSaved: "تم حفظ تفضيلاتك",
      backendNote: "جاهز للربط مع API إعدادات المستخدم"
    }
  },
  en: {
    common: {
      appName: "All In One",
      shortName: "AIO",
      save: "Save changes",
      cancel: "Cancel",
      loading: "Loading...",
      saving: "Saving...",
      success: "Completed successfully",
      email: "Email address",
      password: "Password",
      language: "Language",
      arabic: "العربية",
      english: "English",
      light: "Light",
      dark: "Dark",
      system: "System",
      online: "Online now",
      back: "Back",
      showPassword: "Show password",
      hidePassword: "Hide password"
    },
    validation: {
      required: "This field is required",
      email: "Enter a valid email address",
      password: "Use at least 8 characters with an uppercase letter and a number",
      passwordMatch: "Passwords do not match",
      name: "Enter a name with at least 2 characters",
      otp: "Enter the 6-digit verification code",
      terms: "You must accept the terms and privacy policy",
      imageType: "Use a PNG, JPG, or WebP image",
      imageSize: "The image must be smaller than 2 MB"
    },
    auth: {
      secureAccess: "Secure access to your workspace",
      secureDescription: "One account routes you to the right experience based on your permissions.",
      signIn: "Sign in",
      signInSubtitle: "Enter your account details and we will route you to the correct workspace.",
      signingIn: "Signing in...",
      remember: "Remember me on this device",
      forgot: "Forgot password?",
      noAccount: "New to AIO?",
      createAccount: "Create an account",
      createTitle: "Start with your personal account",
      createSubtitle: "Create a secure account, then join your company through an invitation sent to the same email.",
      fullName: "Full name",
      confirmPassword: "Confirm password",
      agreePrefix: "I agree to the",
      terms: "Terms of use",
      privacy: "Privacy policy",
      creating: "Creating account...",
      haveAccount: "Already have an account?",
      verifyTitle: "Verify your email",
      verifySubtitle: "Enter the 6-digit code we sent to",
      verify: "Verify email",
      verifying: "Verifying...",
      resend: "Resend code",
      resendIn: "Resend available in",
      codeSent: "A new code was sent to your email",
      forgotTitle: "Recover your password",
      forgotSubtitle: "Enter your email and we will send a secure password reset code.",
      sendCode: "Send recovery code",
      sending: "Sending...",
      resetTitle: "Create a new password",
      resetSubtitle: "Choose a strong password you have not used before.",
      resetCode: "Recovery code",
      newPassword: "New password",
      reset: "Save new password",
      passwordRules: "At least 8 characters, uppercase, lowercase, and a number",
      resetSuccess: "Your password was updated. You can sign in now.",
      backToLogin: "Back to sign in",
      testAccounts: "Test accounts",
      testHint: "Choose an account to fill the form and test each permission level.",
      superAdmin: "Platform admin",
      companyAdmin: "Company admin",
      endUser: "End user",
      loginSuccess: "Signed in successfully",
      loginError: "Unable to sign in",
      accountCreated: "Account created and verification code sent",
      verified: "Your email was verified successfully",
      resetCodeSent: "A recovery code was sent to your email",
      demoCode: "Demo code: 123456"
      ,invalidCredentials: "Email or password is incorrect",
      accountExists: "An account already exists for this email",
      invalidCode: "The verification code is invalid or expired",
      accountNotFound: "No account exists for this email",
      registrationExpired: "The registration session expired. Please create the account again",
      authRequired: "Sign in to complete this action",
      currentPasswordIncorrect: "The current password is incorrect"
    },
    shell: {
      search: "Search rooms, files, or members...",
      searchLabel: "Search workspace",
      notifications: "Notifications",
      accountMenu: "Account menu",
      settings: "Settings",
      appearance: "Appearance",
      logout: "Log out",
      help: "Help center",
      upgrade: "Upgrade plan",
      menu: "Open navigation",
      closeMenu: "Close navigation",
      dashboard: "Dashboard",
      home: "Home",
      rooms: "Rooms",
      files: "Content library",
      members: "Members",
      courses: "Programs & courses",
      batches: "Batches & cohorts",
      bookingRequests: "Booking requests",
      announcements: "Announcements",
      meetings: "Meetings",
      tasks: "Tasks",
      calendar: "Calendar",
      bookings: "Book a teacher",
      analytics: "Analytics",
      security: "Security",
      subscription: "Subscription",
      tenants: "Organizations",
      revenue: "Revenue",
      subscriptions: "Subscriptions",
      pricing: "Plans & pricing",
      activity: "Activity log",
      footerRights: "All rights reserved.",
      privacy: "Privacy policy",
      terms: "Terms of service",
      support: "Support"
    },
    settings: {
      title: "Account settings",
      subtitle: "Manage your profile, security, and experience preferences.",
      profile: "Profile",
      security: "Security & sign-in",
      notifications: "Notifications",
      appearance: "Appearance & language",
      profileDescription: "Update your photo, name, and contact details.",
      photo: "Profile photo",
      photoHint: "PNG, JPG, or WebP up to 2 MB.",
      changePhoto: "Change photo",
      removePhoto: "Remove photo",
      role: "Account role",
      company: "Workspace",
      profileSaved: "Account details saved",
      securityDescription: "Manage your password and extra verification methods.",
      currentPassword: "Current password",
      changePassword: "Change password",
      twoFactor: "Two-factor authentication",
      authenticator: "Authenticator app",
      authenticatorHint: "Use an app to generate a temporary code when signing in.",
      sms: "SMS messages",
      smsHint: "Receive a code on your registered mobile number.",
      sessions: "Active sessions",
      sessionsHint: "This device · Cairo, Egypt · Active now",
      signOutOthers: "Sign out other devices",
      notificationDescription: "Choose when and how you receive alerts.",
      emailNotifications: "Email notifications",
      emailNotificationsHint: "New files, invitations, and workspace updates.",
      securityAlerts: "Security alerts",
      securityAlertsHint: "Sign-in attempts, new devices, and sensitive changes.",
      productUpdates: "Product updates",
      productUpdatesHint: "New features and important improvements.",
      appearanceDescription: "Customize appearance and language without affecting account data.",
      theme: "Display mode",
      accent: "Interface color",
      interfaceLanguage: "Interface language",
      settingsSaved: "Preferences saved",
      backendNote: "Ready for the user settings API"
    }
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => window.localStorage.getItem("ain-language") || "ar");

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    window.localStorage.setItem("ain-language", language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    direction: language === "ar" ? "rtl" : "ltr",
    t: translations[language],
    setLanguage(nextLanguage) {
      if (nextLanguage === "ar" || nextLanguage === "en") setLanguageState(nextLanguage);
    },
    toggleLanguage() {
      setLanguageState((current) => current === "ar" ? "en" : "ar");
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}

export function useBilingualText() {
  const { language } = useLanguage();
  return (arabic, english) => language === "ar" ? arabic : english;
}
